config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'static_pages/home'

  # get 'static_pages/help'

  # get 'static_pages/about'

  # get 'static_pages/contact'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clients
  root 'static_pages#home'
  get  '/signup',  to: 'clients#new'
  resources :account_activations, only: [:edit]
  resources :account_administrers, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages,          only: [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_client,   only: [:edit, :update]
  before_action :valid_client, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]    # Case (1)

  def new
  end

  def create
    @client = Client.find_by(email: params[:password_reset][:email].downcase)
    if @client
      @client.create_reset_digest
      @client.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions (this may take a few minutes)."
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found. Please signup."
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:client][:password].empty?                  # Case (3)
      @client.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @client.update_attributes(client_params)          # Case (4)
      log_in @client
      @client.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset."
      redirect_to @client
    else
      render 'edit'                                     # Case (2)
    end
  end

  private

  def client_params
      params.require(:client).permit(:password, :password_confirmation)
    end

  def get_client
    @client = Client.find_by(email: params[:email])
  end

    # Confirms a valid user.
    def valid_client
      unless (@client && @client.activated? &&
        @client.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

  # Checks expiration of reset token.
    def check_expiration
      if @client.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% @pagetitle = "passwordresetpage" %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <div class="passwordresetform">
  <h1>Reset password</h1>
    <%= form_for(@client, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @client.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

      <p class="passwordresetbut"><%= f.submit "Update password", class: "btn btn-primary" %></p>
    <% end %>
  </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<% @pagetitle = "passwordresetpage" %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <div class="passwordresetform">
   <h1>Password Reset</h1>
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <p class="passwordresetbut"><%= f.submit "Reset Password", class: "btn btn-primary" %></p>
    <% end %>
  </div>
  </div>
</div>