config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'static_pages/home'

  # get 'static_pages/help'

  # get 'static_pages/about'

  # get 'static_pages/contact'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clients
  root 'static_pages#home'
  get  '/signup',  to: 'clients#new'
  resources :account_activations, only: [:edit]
  resources :account_administrers, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages,          only: [:create, :destroy]
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :messages, dependent: :destroy
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest

  # before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def Client.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Client.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a client in the database for use in persistent sessions.
  def remember
    self.remember_token = Client.new_token
    update_attribute(:remember_digest, Client.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a client.
  def forget
    update_attribute(:remember_digest, nil)
  end

# Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Activates an account.
  def deactivate
    update_columns(activated: false)
  end

  # Make a client an admin
  def administer
    update_columns(admin: true)
  end

  # Make a client an admin
  def deadminister
    update_columns(admin: false)
  end


  # Sends activation email.
  def send_activation_email
    ClientMailer.account_activation(self).deliver_now
  end


  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = Client.new_token
    update_columns(reset_digest:  Client.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    ClientMailer.password_reset(self).deliver_now
  end

# Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end


  def feed
    Message.where("client_id = ? OR recipient = ?", id, email)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = Client.new_token
      self.activation_digest = Client.digest(activation_token)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :logged_in_client, only: [:index, :edit, :update, :destroy]
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :correct_client,   only: [:edit, :update]
  before_action :admin_client,     only: [:destroy, :index]

  # GET /clients
  # GET /clients.json
  def index
    @clientsinactive = Client.where(activated: false).paginate(page: params[:page])
    @clientsactivenonadmin = Client.where(activated: true).where(admin: false).paginate(page: params[:page])
    @clients = Client.paginate(page: params[:page])
    @clientsadmins = Client.where(admin: true).paginate(page: params[:page])
    if !current_client.admin?
      redirect_to(root_url) 
      flash[:danger] = "You need admin rights to view this page"
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @messages = @client.messages.paginate(page: params[:page])
    redirect_to root_url #unless @client.activated?
  end

  # GET /clients/new
  def new
    @client = Client.new
    redirect_to(root_url) unless !logged_in? || current_client.admin?
  end

  # POST /clients
  # POST /clients.json
  def create
     @client = Client.new(client_params)
    if @client.save
      ClientMailer.account_activation(@client).deliver_now
      flash[:info] = "Please check your email to activate your account (this may take a few minutes)."
      redirect_to root_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json

  def edit
    @client = Client.find(params[:id])
  end

  def update
    if @client.update_attributes(client_params)
      flash[:success] = "Profile updated"
      redirect_to @client
    else
      render 'edit'
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    Client.find(params[:id]).destroy
    flash[:success] = "Client deleted"
    redirect_to clients_url
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in client.
    def logged_in_client
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct client.
    def correct_client
      @client = Client.find(params[:id])
      redirect_to(root_url) unless current_client?(@client) || current_client.admin?
    end

    # Confirms an admin client.
    def admin_client
      redirect_to(root_url) unless current_client.admin?
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.html.erb
<li>

  <%= link_to client.name, client %>
  

  <% if current_client.admin?%>
    | <%= link_to "Edit " + client.name, edit_client_path(client)%>

    <% if !client.admin?%>
    | <%= link_to "Administer " + client.name, edit_account_administrer_path(client), data: { confirm: "Are you sure you want to make " + client.name + " an admin?" }%>
    <% end %>

    <% if !client.activated?%>
    | <%= link_to "Activate " + client.name, edit_account_activation_path(client), data: { confirm: "Are you sure you want to activate " + client.name + "?" }%>
    <% end %>



    
    
  <% end %>

  <% if current_client.admin? && !current_client?(client) %>
    | <%= link_to "Delete " + client.name, client, method: :delete,
                                  data: { confirm: "Are you sure you want to delete " + client.name + "?" } %>

    <% if client.activated? %>
    | <%= link_to "Deactivate " + client.name, edit_account_activation_path(client), data: { confirm: "Are you sure you want to deactivate " + client.name + "?" }%>

  <% end %>
  
     <% if client.admin? %>
    | <%= link_to "Deadminister " + client.name, edit_account_administrer_path(client), data: { confirm: "Are you sure you want to remove admin rights from " + client.name + "?" }%>

  <% end %>

  <% end %>

</li>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <%= render 'shared/error_messages', object: @client %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit 'Submit', class: "btn btn-primary" %>
<% end %>`

app/views/clients/edit.html.erb
<% @pagetitle = "settingspage" %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="settingsform">
    <h1>Update Credentials</h1>
    <%= form_for(@client) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %><br>

      <p class="accounteditbut"><%= f.submit "Save changes", class: "btn btn-primary" %></p>
    <% end %>
  </div>
</div>
</div>

app/views/clients/index.html.erb
<% @pagetitle = "allclientspage" %>
<div class="row">
	<h1>All users</h1><br>

	<table class="table">
		<tbody>
			<tr>
				<td>
					<% if current_client.admin?%>
					<%= link_to "Create New Client", signup_path, class: "btn btn-primary "%>
					<% end %>
				</td>
				<td>
					<%= will_paginate %>

					<h2 class="adminlist">Admins</h2>
					<ul class="clients">
						<%= render @clientsadmins %>
					</ul>
				</td>
			</tr>

			<tr>
				<td>
					<h2 class="inactivelist">Inactive Clients</h2>
					<ul class="clients">
						<%= render @clientsinactive %>
					</ul>
				</td>
				<td>
					<h2 class="activelist">Active Clients</h2>
					<ul class="clients">
						<%= render @clientsactivenonadmin %>
					</ul>
					<%= will_paginate %>
				</td>
			</tr>

		</tbody>
	</table>

</div>

app/views/clients/new.html.erb
<% @pagetitle = "signuppage" %>

<%= form_for(@client) do |f| %>
<div class="row">
      <%= render 'shared/error_messages', object: f.object %>
  <div class="col-md-6">
  <div class="signupform">
  <h1>Sign up</h1>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <p class="createaccountbut"><%= f.submit "Sign up", class: "btn btn-success createaccountbut hvr-pulse-grow" %></p>
    <% end %>
    </div>
  </div>

  <div class="col-md-6">
  <div class="signuptext">
  <h2> Web Development - Responsive Designs </h2>
  <h4> Signup now for a FREE template of your new Website. </h4>
  </div>
  </div>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <aside class="col-md-4">
    <section class="client_info">

        <%= @client.name %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @client.messages.any? %>
      <h3>Messages (<%= @client.messages.count %>)</h3>
      <ol class="messages">
        <%= render @messages %>
      </ol>
      <%= will_paginate @messages %>
    <% end %>
  </div>
</div>