config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'static_pages/home'

  # get 'static_pages/help'

  # get 'static_pages/about'

  # get 'static_pages/contact'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :clients
  root 'static_pages#home'
  get  '/signup',  to: 'clients#new'
  resources :account_activations, only: [:edit]
  resources :account_administrers, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages,          only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="col-md-6 footerlinks">
   <ul class="footernav">
      <li class="footerli" id="lipush"><%= link_to "Home",   root_path, class: "hvr-grow" %></li>
      <li class="footerli"><%= link_to "Contact", 'mailto:syseydi@gmail.com?subject=Hello there Seydi!', class: "hvr-grow" %></li>
    </ul> 
    </div>

<%if !logged_in? %>
    <div class="col-md-6 footersignup">
    <%= link_to "Sign Up", signup_path, class: "btn btn-success footersignupbut hvr-pulse-grow" %>
    </div>
    <% end %>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("https://s3.amazonaws.com/seydisigns/Logo.png"), root_path, class: "logoimglink hvr-grow" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right animated fadeInRight">
        <li><%= link_to "Home", root_path, class: "hvr-grow" %></li>

        <% if logged_in? %>
        <% if current_client.admin?%>
        <li><%= link_to "Clients", clients_path, class: "hvr-grow" %></li>
        <% end %>
        <% else %>
        <li><%= link_to "Sign Up", signup_path, class: "hvr-grow" %></li>
        <li><%= link_to "Log in", login_path, class: "hvr-grow" %></li>
        <% end %>
        <li><%= link_to "Upwork", "http://www.upwork.com/o/profiles/users/_~01d4a1ce368441bc0f/", class: "hvr-grow"
        %>
        <li><%= link_to "Email Me", "mailto:syseydi@gmail.com?subject=Hello there Seydi!", class: "hvr-grow" %></li>
        <% if logged_in? %>
        <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <!-- <li><%= link_to "Profile", current_client %></li> -->
          <li><%= link_to "Settings", edit_client_path(current_client), class: "hvr-grow" %></li></li>
          <!-- <li class="divider"></li> -->
          <li>
            <%= link_to "Log out", logout_path, method: "delete", class: "hvr-grow" %>
          </li>
        </ul>
      </li>
      <% end %>
    </ul>
  </div><!--/.nav-collapse -->
</div><!--/.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Seydisigns</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="assets/jquery.fadeshow-0.1.1.min.css">
  <script src="assets/jquery.fadeshow-0.1.2.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="https://s3.amazonaws.com/seydibio/pb.png"/>

</head>

<body class="<%= @pagetitle %>">
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>